kanban/src/main/java/kanban/entities/SavedGame.java
package kanban.entities;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class SavedGame {

	@Id
	private int uid;
	private int totalPoints;
	private String userName;
	private Date date;
	private int levelNumber; 
	private int rank;
	
	// Getter and Setter
	
	public int getUid() {
		return uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}
	public int getTotalPoints() {
		return totalPoints;
	}
	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public int getLevelNumber() {
		return levelNumber;
	}
	public void setLevelNumber(int levelNumber) {
		this.levelNumber = levelNumber;
	}
	public int getRank() {
		return rank;
	}
	public void setRank(int rank) {
		this.rank = rank;
	}
}

kanban/src/main/java/kanban/model/Block.java
package kanban.model;

import java.util.ArrayList;
import java.util.List;

public class Block {

	public static final int UP = 0;
	public static final int RIGHT = 1;
	public static final int DOWN = 2;
	public static final int LEFT = 3;
	private static final int NUMBEROFNEIGHBOURS = 4;
	 
	private Colour colour;
	private List<Block> neighbours;
	
	public Block(Colour colour) {
		this.colour = colour;
		neighbours= new ArrayList<Block>();
		for (int i = 0; i< NUMBEROFNEIGHBOURS; i++){
			neighbours.add(i, null);
		}
	}
	
	public boolean isClickable(){
		if(colour == Colour.TRANSPARENT) {
			return false;
		}
		for (Block neighbour : getNeighbours()) {
			if(neighbour != null && colour == neighbour.getColour()){
				return true;
			}
		}
		return false;
	}
	
	public boolean isTransparent() {
		if(colour == Colour.TRANSPARENT) {
			return true;
		}
		return false;
	}
	

	
	// Getter and Setter
	
	
	public Colour getColour() {
		return colour;
	}

	public void setColour(Colour colour) {
		this.colour = colour;
	}

	public List<Block> getNeighbours() {
		return neighbours;
	}
}

kanban/src/main/java/kanban/model/Board.java
package kanban.model;


import java.util.List;

public class Board {

	public static final int WIDTH =  40;
	public static final int HEIGHT = 20;
	private List<Block> blockList;

	public Board(List<Block> blockList) {
		this.blockList = blockList;
	}
	
	
	public int getWidth() {
		return WIDTH;
	}

	public int getHeight() {
		return HEIGHT;
	}

	public List<Block> getBlockList() {
		return blockList;
	}
	
}

kanban/src/main/java/kanban/model/Colour.java
package kanban.model;

import java.util.Random;

public enum Colour {
	AQUA(),
	FUCHSIA(),
	GREEN(),
	LIME(),
	NAVY(),
	ORANGE(),
	PURPLE(),
	RED(),
	TEAL(),
	YELLOW(),
	TRANSPARENT();
	
	private static final Colour[] VALUES = values();
	private static final int LENGTH = VALUES.length;
	private static Random randomizer = new Random();

	public static Colour getRandomColour() {
		return VALUES[randomizer.nextInt(LENGTH)];
	}
	
	public String toString() {
		return name().toLowerCase();
	}
}

kanban/src/main/java/kanban/model/CurrentGame.java
package kanban.model;


public class CurrentGame {

	private int totalPoints;
	private int currentPoints;
	private int currentNumberOfBlocks;
	private Board board;

	private Level currentLevel;
	private int currentTime;

	public CurrentGame() {
		this.currentLevel = Level.LEVEL1;
		this.totalPoints = 0;
	}
	
	public boolean isWon() {
		if(this.currentNumberOfBlocks <= this.currentLevel.getGoal()){
			return true;
		}
		return false;
	}

	
	// Getter and Setter
	
	public int getCurrentTime() {
		return currentTime;
	}

	public void setCurrentTime(int currentTime) {
		this.currentTime = currentTime;
	}
	
	public int getCurrentPoints() {
		return currentPoints;
	}
	
	public void setCurrentPoints(int currentPoints) {
		this.currentPoints = currentPoints;
	}
	
	public int getCurrentNumberOfBlocks() {
		return currentNumberOfBlocks;
	}
	
	public void setCurrentNumberOfBlocks(int currentNumberOfBlocks) {
		this.currentNumberOfBlocks = currentNumberOfBlocks;
	}
	
	public Level getCurrentLevel() {
		return currentLevel;
	}
	
	public void setCurrentLevel(Level currentLevel) {
		this.currentLevel = currentLevel;
	}

	public int getTotalPoints() {
		return totalPoints;
	}

	public Board getBoard() {
		return board;
	}
	
	public void setBoard(Board board) {
		this.board = board;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}
}

kanban/src/main/java/kanban/model/Level.java
package kanban.model;

public enum Level {
	
	LEVEL1(3,30),
	LEVEL2(3,20),
	LEVEL3(4,30),
	LEVEL4(4,20);
	
	private int numberOfColours;
	private int goal;
	
	private Level(int numberOfColours, int leftOverBlocks) {
		this.numberOfColours = numberOfColours;
		this.goal = leftOverBlocks;
	}

	public int getNumberOfColours() {
		return numberOfColours;
	}

	public int getGoal() {
		return goal;
	}

	public String getLevelNumber() {
		return this.name().substring(5); 
	}
	
	public int getLevelNumberAsInt() {
		return Integer.parseInt(getLevelNumber());
	}
	
	public boolean isLastlevel() {
		if(this == LEVEL4) {
			return true;
		}
		return false;
	}
}

kanban/src/main/java/kanban/controller/GameController.java
package kanban.controller;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.primefaces.context.RequestContext;
import kanban.services.Timer;
import kanban.model.Block;
import kanban.model.Board;
import kanban.model.CurrentGame;
import kanban.model.Level;
import kanban.services.BlockDeleter;
import kanban.services.BoardSetter;
import kanban.services.GameStatus;
import kanban.services.MoveBlocks;

@ManagedBean
@SessionScoped
public class GameController {

	public static final String FORCERELOAD = "?faces-redirect=true";
	
	private CurrentGame game;
	private Timer timer;
	private BoardSetter boardSetter;

	@PostConstruct
	public void init() {
		game = new CurrentGame();
	}
	
	public String startGame() {
		game = new CurrentGame();
		boardSetter = new BoardSetter();
		startLevel();
		this.timer = new Timer(game);
		return "game" + FORCERELOAD;
	}
	
	public void makeMoveInGame(Block block) {
		if (block.isClickable()) {
			int deletedBlocks = deleteBlocks(block);
			moveBlocks();
			updateStatistics(deletedBlocks);
			if(!boardSetter.clickableBlockExists()) {
				if(game.isWon()) {
					RequestContext.getCurrentInstance().execute("gameWon.show()");
				} else {
					RequestContext.getCurrentInstance().execute("gameLost.show()");
				}
			}
		}
	}
	
	private int deleteBlocks(Block block){
		BlockDeleter deleter = new BlockDeleter(block);
		return deleter.deleteBlocksWithSameColour(block);
	}

	private void moveBlocks() {
		MoveBlocks mover = new MoveBlocks(game.getBoard().getBlockList());
		mover.moveBlocks();
		mover.moveColums();
	}
	
	private void updateStatistics(int deletedBlocks) {
		GameStatus status = new GameStatus(game);
		status.updateNumberOfBlocks(deletedBlocks);
		status.updatePoints(deletedBlocks);
	}
	
	public void startLevel() {
		game.setCurrentNumberOfBlocks(Board.HEIGHT * Board.WIDTH);
		game.setCurrentPoints(0);
		game.setCurrentTime(0);
		game.setBoard(boardSetter.initBoard(game.getCurrentLevel()));
	}
	
	private void updateLevel() {
		int levelnumber = game.getCurrentLevel().getLevelNumberAsInt()+1;
		game.setCurrentLevel(Level.valueOf("LEVEL" + levelnumber));
	}
	
	

	
	//Navigation for Pages
	
	public String startNewLevel() {
		updateLevel();
		startLevel();
		return "game"+ FORCERELOAD;
	}


	public String toIndex(){
		return "intro" + FORCERELOAD;
	}
	
	public String toResult(){
		game.setTotalPoints(game.getCurrentPoints()+game.getTotalPoints());
		return "result" + FORCERELOAD;
	}
	
	public String toSaveGamePage(){
		return "savepage" + FORCERELOAD;
	}
	
	public String toLevelFinished(){
		game.setTotalPoints(game.getTotalPoints()+game.getCurrentPoints());
		if(game.getCurrentLevel().isLastlevel()) {
			return "result" + FORCERELOAD;
		}
		return "levelFinished" + FORCERELOAD;
	}
	
	public String toRanking(){
		return "ranking" + FORCERELOAD;
	}

	
	//Getter and Setter
	
	public Timer getTimer() {
		return timer;
	}
	
	public CurrentGame getGame() {
		return game;
	}

	public BoardSetter getBoardSetter() {
		return boardSetter;
	}
}

kanban/src/main/webapp/game.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/Game.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/Colours.css"/>
	<title>Spiel</title>
</h:head> 
<body> 

<!-- HEADER STATISTIKEN -->
	<div id="header">
		<div class="header-level">
			Level <h:outputText value="#{gameController.game.currentLevel.levelNumber}" />
		</div>
		<div class="wrap">
			<i class="fa fa-square header-left-icon-font"></i>
			<h:outputText id="blocks" styleClass="header-left-text" value="Steine: #{gameController.game.currentNumberOfBlocks}" />	
			<i class="fa fa-tachometer header-left-icon-font"></i>
			<h:outputText id="points" styleClass="header-left-text" value="Punkte: #{gameController.game.currentPoints}" />
			<i class="fa fa-clock-o header-left-icon-font"></i>
			<h:form id="form">  
    			<h:outputText id="time" styleClass="header-left-text" value="Zeit: #{gameController.timer.timeToMinutes()}" />  
     			<p:poll widgetVar="poll" interval="1" listener="#{gameController.timer.incrementTime()}" update="time" />  
			</h:form> 
			<h:outputText styleClass="header-right-text" value="Ziel: höchstens #{gameController.game.currentLevel.goal} Steine übrig" />
			<i class="fa fa-unlock header-right-icon-font"></i>
		</div>
	</div>

<!-- SPIELFELD -->	
	<div>
		<p:dataGrid id="board" var="block" value="#{gameController.game.board.blockList}" columns="#{gameController.game.board.width}">
			<p:commandButton disabled="#{!gameController.timer.running}" update="board, :blocks, :points" value="" actionListener="#{gameController.makeMoveInGame(block)}" styleClass="#{block.colour.toString()} block-game "/>
		</p:dataGrid>
	</div>
	
<!-- FOOTER BUTTONS -->
	<div class="center-inline">
		<h:panelGroup id="footer">
			<p:commandLink id="pauseGame" rendered="#{gameController.timer.running}"  action="#{gameController.timer.updateRunning(false)}" onclick="PF('poll').stop();" update="#{p:component('footer')}, #{p:component('tooltips')}" styleClass="link-fix game-navigation">
				<i class="fa fa-pause"></i>
			</p:commandLink>
		
			<p:commandLink id="continueGame" rendered="#{!gameController.timer.running}" action="#{gameController.timer.updateRunning(true)}" onclick="PF('poll').start();" update="#{p:component('footer')}, #{p:component('tooltips')}, #{p:component('board')}" styleClass="link-fix game-navigation">
				<i class="fa fa-play"></i>
			</p:commandLink>
		
			<p:commandLink id="stopGame" onclick="PF('poll').stop();PF('cancelGame').show();" styleClass="link-fix game-navigation">
				<i class="fa fa-stop"></i>
			</p:commandLink> 
			
			<p:commandLink id="inGameHelp" onclick="PF('poll').stop();PF('help').show();" styleClass="link-fix game-navigation">
				<i class="fa fa-question"></i>
			</p:commandLink>	
		</h:panelGroup>
		
		<h:panelGroup id="tooltips">
			<!-- FOOTER BUTTON TOOLTIPS -->
			<p:tooltip value="Spiel beenden" for="stopGame"/>
			<p:tooltip value="Spiel pausieren (Zeit hält an)" for="pauseGame" />
			<p:tooltip value="Spiel fortsetzen (Zeit läuft weiter)" for="continueGame" />
			<p:tooltip value="Hilfe" for="inGameHelp"/>
		</h:panelGroup>
	</div>
	
<!-- POPUP LEVELZIEL -->	
	<p:dialog id="level-goal" modal="true" widgetVar="levelGoal" onShow="PF('poll').stop();"
		header="Ziel" rendered="#{gameController.timer.timeToMinutes() eq '00:00'}" visible="true">
		<h:form styleClass="center-inline">
			<div class="">
				<h:outputText value="Ziel: höchstens #{gameController.game.currentLevel.goal} Blöcke bleiben übrig" />
			</div>
			<div class="center-text">
				<p:commandButton value="Spielen" onclick="PF('poll').start();PF('levelGoal').hide();" styleClass="extraSmallButton" />
			</div>
		</h:form>
	</p:dialog>
		
<!-- POPUP ABBRECHEN -->
	<p:dialog id="cancelGame" widgetVar="cancelGame" header="Spiel abbrechen" modal="true">
		<h:form>
			<div>
				<h:outputText value="Bist du sicher, dass du das Spiel beenden möchtest?" />
			</div>
			<div class="center-inline">
				<p:commandButton action="#{gameController.toResult()}" value="Ja" styleClass="extraSmallButton"/>
				<p:commandButton value="Nein" onclick="PF('poll').start();PF('cancelGame').hide();" styleClass="extraSmallButton"/>
			</div>
		</h:form>
	</p:dialog>
	
<!-- POPUP HILFE -->
	<p:dialog id="help" showEffect="fade" widgetVar="help" header="Hilfe">
		<h:form>
			<h2>Ziel</h2>
			<div>Entferne genug Blöcke aus dem Board, um das Levelziel zu erreichen</div>
			<h2>Vorgehen</h2>
			<div>Nur Blöcke mit mindestens einem gleichfarbigen Nachbarn können weggeklickt werden</div>
			<h2>Spiel abbrechen</h2>
			<div>Klicke den Stop-Button unterhalb des Spielfelds</div>
			<h2>Spiel anhalten</h2>
			<div>Klicke den Pause-Button unterhalb des Spielfelds, um die Zeit anzuhalten</div>
			<h2>Hilfe</h2>
			<div>Klicke den Hilfe-Button unterhalb des Spielfelds, um dieses Popup erneut anzuzeigen.</div>
			<div class="center-inline">
				<p:commandButton value="Spielen" onclick="PF('poll').start();PF('help').hide();" styleClass="extraSmallButton"/>
			</div>
		</h:form>
	</p:dialog>	
		
<!-- POPUP SPIEL GEWONNEN -->	
	<p:dialog id="gameWon" modal="true" widgetVar="gameWon" onShow="PF('poll').stop();" header="Gewonnen">
		<h:form styleClass="center-inline">
			<div>
				<h:outputText value="Level geschafft!" />
			</div>
			<div class="center-text">
				<p:commandButton value="OK" action="#{gameController.toLevelFinished()}" styleClass="extraSmallButton" />
			</div>
		</h:form>
	</p:dialog>

<!-- POPUP SPIEL VERLOREN -->	
	<p:dialog id="gameLost" modal="true" widgetVar="gameLost" onShow="PF('poll').stop();" header="Verloren">
		<h:form styleClass="center-inline">
			<div>
				<h:outputText value="Levelziel nicht erreicht" />
			</div>
			<div class="center-text">
				<p:commandButton value="OK" action="#{gameController.toResult()}" styleClass="extraSmallButton"/>
			</div>
		</h:form>
	</p:dialog>
</body> 
</html>

kanban/src/main/webapp/intro.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/Intro.css"/>
	<title>Introseite</title>
</h:head> 
<body> 
	<h:form>
		<div class="center-elements top-space">
			<h1>clear blocks </h1>
			
			<div id="wrapper">
				<div id="instruction-box" >
					<h3>Ziel</h3>
					<div>Entferne genug Blöcke aus dem Board, um das Levelziel zu erreichen</div>
					<h3>Vorgehen</h3>
					<div>Nur Blöcke mit mindestens einem gleichfarbigen Nachbarn können weggeklickt werden</div>
					<h3>Level</h3>
					<div>
						LEVEL 1: 3 Farben, 30 Blöcke übrig
					</div>
					<div>
						LEVEL 2: 3 Farben, 20 Blöcke übrig
					</div>	
					<div>
						LEVEL 3: 4 Farben, 30 Blöcke übrig
					</div>	
					<div>
						LEVEL 4: 4 Farben, 20 Blöcke übrig
					</div>
				</div>
			</div>
			<div id="button-box">
				<h:commandButton value="Rangliste" action="#{gameController.toRanking()}" styleClass="smallButton" />
				<h:commandButton value="Starten" action="#{gameController.startGame()}" styleClass="smallButton"/>
			</div>			
		</div>
	</h:form>
</body> 
</html>

kanban/src/main/webapp/levelFinished.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Zwischenergebnis</title>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css"/>
</h:head> 
<body>
<h:form>
 	<h1>Glückwunsch!</h1>
	<div class="opacityBox text-big top-space center-inline">
		<h:outputText value="Du hast #{gameController.game.currentPoints} Punkte" />
		<div><h:outputText value="in Level #{gameController.game.currentLevel.levelNumber} erreicht"/></div>
		<div>und kommst ins nächste Level.</div>
		<div>Dein momentaner Gesamtpunktestand:</div> 
		<h:outputText value="#{gameController.game.totalPoints} Punkte"/>
	</div>
	<div class="center-elements">
		<p:commandButton styleClass="bigButton p-command-button-fix" value="Speichern" onclick="PF('saveDialog').show();"/>
		<p:commandButton styleClass="bigButton p-command-button-fix" action="#{gameController.startNewLevel()}" value="Weiterspielen"/>
		<p:commandButton styleClass="bigButton p-command-button-fix" value="Startseite" onclick="PF('dialog').show();"/>
	</div>
</h:form>
	
	<p:dialog id="popupNewGame" showEffect="fade" widgetVar="dialog" modal="true">
		<h:form>
			<h:outputText value="Willst du das Spiel wirklich beenden?" />
			<div class="commitButtons">
				<p:commandButton action="#{gameController.toIndex()}" value="Ja" styleClass="extraSmallButton"/>
				<p:commandButton value="Nein" onclick="hide();" styleClass="extraSmallButton" />
			</div>
		</h:form>
	</p:dialog>

  	<p:dialog id="popupSave" widgetVar="saveDialog" modal="true" header="Speichern">
		<h:form id="name-input">
		<p:messages autoUpdate="true" />
			<span class="big-text">
					Name:
					<p:inputText id="username" required="true"
						requiredMessage="Bitte gib zum Speichern einen Namen an">
						<f:validateRegex pattern="[a-zA-Z0-9äöüÄÖÜß]+"/>
						<f:validateLength maximum="20" minimum="2"/>
					</p:inputText>
				</span>
				
				<div class= "center-inline">
					<p:commandButton action="#{dBConnector.toSaveGame(gameController.game)}" value="speichern" styleClass="button"/>
				</div>
		</h:form>
  </p:dialog>

</body> 
</html>

kanban/src/main/webapp/ranking.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Rangliste</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/Ranking.css"/>
</h:head> 
<body> 
	<h1>Rangliste</h1>
	<p:dataTable id="ranking-table" var="result" value="#{dBConnector.allSavedGames}"
		paginator="true" paginatorAlwaysVisible="false" rows="7"
		styleClass="ranking-table center-elements">
  		<p:column styleClass="text-right">
			<f:facet name="header">  
                <h:outputText value="Rang" />  
            </f:facet>  
            <h:outputText value="#{result.rank}" />
		</p:column>
		<p:column styleClass="text-left">
			<f:facet name="header">  
                <h:outputText value="Name" />  
            </f:facet>  
            <h:outputText value="#{result.userName}" />
		</p:column>
		<p:column styleClass="text-right">
			<f:facet name="header">  
                <h:outputText value="Punkte" />  
            </f:facet>  
            <h:outputText value="#{result.totalPoints}" />
		</p:column>
		<p:column styleClass="text-center">
			<f:facet name="header">  
                <h:outputText value="Level" />  
            </f:facet>  
            <h:outputText value="Level #{result.levelNumber}" />
		</p:column>
		<p:column styleClass="text-center">
			<f:facet name="header">  
                <h:outputText value="Datum" />  
            </f:facet>  
            <h:outputText value="#{result.date}" />
		</p:column>
	</p:dataTable>
	<div class="center-inline">
		<h:form>
			<h:commandButton value="Startseite" action="#{gameController.toIndex()}" styleClass="smallButton" />
		</h:form>
	</div>
</body> 
</html>

kanban/src/main/webapp/result.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Ergebnis</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css"/>
	</h:head> 
<body>
	<div class="opacityBox text-big top-space center-inline">	
		<p:panel id ="last-level-text" rendered="#{gameController.game.currentLevel.lastlevel and gameController.game.won}">
			<div class="text-big">Herzlichen Glückwunsch!</div>
			<div class="text-big">Du hast alle Level geschafft und</div>
		</p:panel>
		<h:outputText value="Du hast" rendered="#{!gameController.game.won}" />
		<h:outputText value=" #{gameController.game.totalPoints} Punkte" styleClass="auszeichnungstext"/>
		<div>nach</div> 
		<h:outputText value="Level #{gameController.game.currentLevel.levelNumber}" styleClass="auszeichnungstext"/>
		<div>erreicht.</div>
	</div>
	<div class="center-inline">
		<h:form>
			<p:commandButton value="Speichern"  rendered="#{gameController.game.totalPoints != 0}" onclick="PF('saveDialog').show();" styleClass="bigButton p-command-button-fix"/>
			<p:commandButton value="Startseite" rendered="#{gameController.game.totalPoints != 0}" onclick="PF('dialog').show();" styleClass="bigButton p-command-button-fix"/>
			<p:commandButton value="Startseite" rendered="#{gameController.game.totalPoints == 0}" action="#{gameController.toIndex()}" styleClass="bigButton p-command-button-fix"/>
		</h:form>
	</div>

	<p:dialog id="popupNewGame" widgetVar="dialog" modal="true">
		<h:form>
			<h:outputText value="Willst du das Spiel wirklich nicht speichern und ein Neues starten?" />
			<div class="commitButtons center-inline">
				<p:commandButton action="#{gameController.toIndex()}" value="Ja" styleClass="extraSmallButton"/>
				<p:commandButton value="Nein" onclick="hide();" styleClass="extraSmallButton">
				</p:commandButton>
			</div>
		</h:form>
	</p:dialog>
	
	  	<p:dialog id="popupSave" widgetVar="saveDialog" modal="true" header="Speichern">
		<h:form id="name-input">
		<p:messages autoUpdate="true" />
			<span class="big-text">
					Name:
					<p:inputText id="username" required="true"
						requiredMessage="Bitte gib zum Speichern einen Namen an">
						<f:validateRegex pattern="[a-zA-Z0-9äöüÄÖÜß]+"/>
						<f:validateLength maximum="20" minimum="2"/>
					</p:inputText>
				</span>
				
				<div class= "center-inline">
					<p:commandButton action="#{dBConnector.toSaveGame(gameController.game)}" value="speichern" styleClass="button"/>
				</div>
		</h:form>
  </p:dialog>

</body> 
</html>